import './style.css';
import { bootstrap } from './gameplay/engine.ts';
import { startAdvancedWeaponController } from './gameplay/advancedWeaponController.ts';
import { startDynamicPrecisionReticle } from './gameplay/dynamicPrecisionReticle.ts';
import { startPrecisionShotRuntime } from './gameplay/precisionShotRuntime.ts';
import { startLocalHitscanRangeGuard } from './gameplay/localHitscanRangeGuard.ts';
import { startSpawnController } from './gameplay/spawnController.ts';
import { startKillAmmoReset } from './gameplay/killAmmoReset.ts';
import { startCombatFeedback } from './gameplay/combatFeedback.ts';
import { startDeathmatchScore } from './gameplay/deathmatchScore.ts';
import { startRemoteRobotMotion } from './gameplay/remoteRobotMotion.ts';
import { startMapSpawnMarkers } from './gameplay/mapSpawnMarkers.ts';
import { startHostRemoteSync } from './net/hostRemoteSync.ts';
import { startLobbyPresenceSync } from './net/lobbyPresenceSync.ts';
import { startPvpTimingTuning } from './net/pvpTuning.ts';
import { startPvpHardening } from './net/pvpHardening.ts';
import { startNetworkStabilityFix } from './net/networkStabilityFix.ts';
import { startAdaptiveSnapshotRate } from './net/adaptiveSnapshotRate.ts';
import { startCombatEventBridge } from './net/combatEventBridge.ts';
import { startSessionLifecycleHardening } from './net/sessionLifecycleHardening.ts';
import { startRemoteShotPresentation } from './net/remoteShotPresentation.ts';
import { startTracerPresentationFix } from './gameplay/tracerPresentationFix.ts';
import { startLiveMapOverlay } from './gameplay/liveMapOverlay.ts';
import { startMusicSourceGain } from './audio/musicSourceGain.ts';
import { startNaturalSunRays } from './world/naturalSunRays.ts';
import { startPerformancePack } from './performance/performancePack.ts';
import { startCacheIntegrity } from './performance/cacheIntegrity.ts';
import { startLocalTelemetry } from './performance/localTelemetry.ts';
import { startAdaptiveRenderScale } from './performance/adaptiveRenderScale.ts';
import { startTelemetryDetails } from './performance/telemetryDetails.ts';

// Install lightweight protocol/runtime patches before any game/session objects are created.
startNetworkStabilityFix();
startPvpHardening();
startCombatEventBridge();
startTracerPresentationFix();
startNaturalSunRays();

bootstrap();
startSessionLifecycleHardening();
startPrecisionShotRuntime();
startLocalHitscanRangeGuard();
startAdvancedWeaponController();
startDynamicPrecisionReticle();
startLobbyPresenceSync();
startPvpTimingTuning();
startHostRemoteSync();
startAdaptiveSnapshotRate();
startRemoteShotPresentation();
startRemoteRobotMotion();
startKillAmmoReset();
startCombatFeedback();
startDeathmatchScore();
startSpawnController();
startLiveMapOverlay();
startMapSpawnMarkers();
startMusicSourceGain();
startPerformancePack();
startCacheIntegrity();
startLocalTelemetry();
startAdaptiveRenderScale();
startTelemetryDetails();
