export const WORLD_CENTER_X = 0;
export const WORLD_CENTER_Z = 0;

export const CENTRAL_HUB_RADIUS = 40;
export const CENTRAL_SUPPLY_MIN_RADIUS = 52;
export const CENTRAL_SUPPLY_MAX_RADIUS = 150;
export const SUPPLY_PICKUP_RADIUS = 3.25;
export const SUPPLY_AUTHORITY_SLACK = 1.75;

export const CENTRAL_SUPPLY_AUTHORITY_MIN_RADIUS =
  CENTRAL_SUPPLY_MIN_RADIUS - SUPPLY_PICKUP_RADIUS - SUPPLY_AUTHORITY_SLACK;
export const CENTRAL_SUPPLY_AUTHORITY_MAX_RADIUS =
  CENTRAL_SUPPLY_MAX_RADIUS + SUPPLY_PICKUP_RADIUS + SUPPLY_AUTHORITY_SLACK;

export const GIANT_CRATER_CENTER_X = 1200;
export const GIANT_CRATER_CENTER_Z = 1200;
export const GIANT_CRATER_RADIUS = 250;
