import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

function gitSha() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

function safeBuildId(raw) {
  const normalized = String(raw || 'dev').trim().replace(/[^a-zA-Z0-9._-]/g, '_');
  return (normalized || 'dev').slice(0, 80);
}

const buildId = safeBuildId(
  process.env.VERCEL_GIT_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  process.env.GONE_BUILD_ID ||
  gitSha() ||
  'dev',
);

const generatedDir = path.join(root, 'src', 'generated');
const publicDir = path.join(root, 'public');
fs.mkdirSync(generatedDir, { recursive: true });
fs.mkdirSync(publicDir, { recursive: true });

fs.writeFileSync(
  path.join(generatedDir, 'buildVersion.ts'),
  `// Generated by scripts/generate_build_version.mjs\nexport const BUILD_ID = ${JSON.stringify(buildId)} as const;\n`,
);

fs.writeFileSync(
  path.join(publicDir, 'version.json'),
  `${JSON.stringify({ buildId, generatedAt: new Date().toISOString() }, null, 2)}\n`,
);

console.log(`[build-version] ${buildId}`);
