/**
 * ADS movement scaling is intentionally disabled at browser startup.
 *
 * The production build replaces the checked-in JavaScript fallback with the
 * wasm-bindgen wrapper generated by `wasm-pack`. Named exports from that
 * wrapper are not callable until the default WASM initializer has completed.
 * This module used to start from the client runtime while the app was still at
 * the menu, so its first animation frame could call `set_movement_scale`
 * before `gameplay/engine.ts` had awaited `init()`, crashing the client.
 *
 * Keep this startup hook as a compatibility surface for the runtime graph, but
 * do not touch game-core here. ADS still changes look sensitivity, weapon
 * handling and presentation through their existing owners; only the optional
 * 0.84 movement-speed modifier is suspended until movement scaling is wired to
 * an explicit post-WASM gameplay lifecycle transition.
 */
export function startAimMovementTuning(): void {
  // Deliberate no-op: game-core bindings must not be called before WASM init.
}
